# Generated by Django 4.0.2 on 2022-03-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('log_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=250)),
                ('exception_message', models.CharField(max_length=250)),
                ('exception_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
