# Generated by Django 4.0.2 on 2022-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlog',
            name='view_name',
            field=models.CharField(default='Empty', max_length=250),
        ),
    ]
