# Generated by Django 4.0.2 on 2022-03-12 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception_handling', '0002_exceptionlog_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlog',
            name='exception_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
