# Generated by Django 4.0.2 on 2022-03-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_user_1',
            field=models.CharField(default='Empty', max_length=250),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_user_2',
            field=models.CharField(default='Empty', max_length=250),
        ),
    ]
