# Generated by Django 4.0.2 on 2022-03-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_room_user_1_chatroom_room_user_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_user_1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_user_2',
        ),
    ]
