# Generated by Django 4.0.2 on 2022-03-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_chatroom_room_user_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_user_1',
            field=models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, related_name='room_user_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_user_2',
            field=models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, related_name='room_user_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
