# Generated by Django 4.0.2 on 2022-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_room_user_1_chatroom_room_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
