# Generated by Django 4.0.2 on 2022-03-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.CharField(max_length=100),
        ),
    ]
