# Generated by Django 4.0.2 on 2022-03-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_time',
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(default='empty', max_length=250),
        ),
    ]
