# Generated by Django 3.1 on 2022-01-29 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('user_follower_count', models.IntegerField(default=0)),
                ('user_following_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_has_follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_1', to=settings.AUTH_USER_MODEL)),
                ('user_is_following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/posts')),
                ('image_caption', models.CharField(max_length=250)),
                ('image_liked_count', models.IntegerField(default=0)),
                ('image_liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_3', to=settings.AUTH_USER_MODEL)),
                ('profile_id', models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
                ('user', models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
