# Generated by Django 3.1 on 2022-01-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0002_auto_20220129_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_has_follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_is_following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
