# Generated by Django 3.1 on 2022-01-29 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0003_auto_20220129_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some_random_string_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
