# Generated by Django 3.1 on 2022-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20220129_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
