# Generated by Django 3.1 on 2022-01-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20220129_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_count',
            new_name='post_count',
        ),
    ]
