# Generated by Django 3.1 on 2022-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_auto_20220129_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Empty', max_length=500, null=True),
        ),
    ]
