# Generated by Django 3.1 on 2022-02-01 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0007_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_liked_by',
        ),
        migrations.AddField(
            model_name='image',
            name='image_liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='some_random_string_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
