# Generated by Django 4.0.2 on 2022-02-28 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0009_auto_20220201_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('fr_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ManyToManyField(blank=True, null=True, related_name='requestee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
