# Generated by Django 3.1 on 2022-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_username',
            field=models.CharField(default='Empty', max_length=250),
        ),
        migrations.AddField(
            model_name='reply',
            name='replier_username',
            field=models.CharField(default='Empty', max_length=250),
        ),
    ]
